/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT loop.cdb */

/*  Include Header Files  */
#include <std.h>
#include <hst.h>
#include <swi.h>
#include <tsk.h>
#include <log.h>
#include <sem.h>
#include <sts.h>

#ifdef __cplusplus
extern "C" {
#endif

extern far HST_Obj RTA_fromHost;
extern far HST_Obj RTA_toHost;
extern far SWI_Obj KNL_swi;
extern far TSK_Obj TSK_idle;
extern far TSK_Obj ZCPYLINK_TSK_OBJ;
extern far TSK_Obj TSK0;
extern far TSK_Obj TSK1;
extern far TSK_Obj TSK2;
extern far TSK_Obj TSK4;
extern far TSK_Obj TSK5;
extern far TSK_Obj TSK6;
extern far LOG_Obj LOG_system;
extern far LOG_Obj trace;
extern far SEM_Obj SEM1;
extern far SEM_Obj SEM2;
extern far SEM_Obj SEM3;
extern far SEM_Obj SEM4;
extern far SEM_Obj SEM5;
extern far SEM_Obj SEM0;
extern far SEM_Obj SEM6;
extern far STS_Obj IDL_busyObj;
extern far STS_Obj STS0;


#ifdef __cplusplus
}
#endif /* extern "C" */
