#pragma once

#define ZONE_INFO       1                                               /*  0：不打印中间信息           */
#define ZONE_ERROR      1

#define EN_9192_DETECT  1
#define EN_SMV          1
#define EN_GOOSE_DETECT 1

#ifndef min
#define min(x,y) ((x) < (y) ? (x) : (y))
#endif
#ifndef max
#define max(x,y) ((x) > (y) ? (x) : (y))
#endif

//下面两个宏只用于测试
// #define TEST_DETECT
// #define TEST_DETECT_FILTER
// #define TEST
#define EN_SAVE_TO_FILE         1



typedef enum {
    _RECV_NONE = -1,                                                    /*  不接收任何数据              */
    _RECV_NUM = 0,                                                      /*  按固定数目接收              */
    _RECV_TIME,                                                         /*  按时间接收                  */
    _RECV_LOOP                                                          /*  循环接收                    */
}RecvFrameMode_e;                                                       /*  光口接收模式                */

#define APP_PRIO                    100                                 /*  应用程序线程的优先级        */


//抖动测试、异常分析数据存储地址  依据《PNS_602通信协议-v2_12-6-12(修正).doc》
#define NetFrameExcAddr_A           0x4000
#define NetFrameExcDataLen_A        8                                   /*  数据长度 按16bit为单位      */
#define NetFrameExcAddr_B           0x4008
#define NetFrameExcDataLen_B        8                                   /*  数据长度 按16bit为单位      */

#define FT3FrameExcAddr_A           0x4010
#define FT3FrameExcDataLen_A        8                                   /*  数据长度 按16bit为单位      */
#define FT3FrameExcAddr_B           0x4018
#define FT3FrameExcDataLen_B        8                                   /*  数据长度 按16bit为单位      */

#define NetWobbleTestAddr_A         0x4020
#define NetWobbleTestDataLen_A      9                                   /*  数据长度 按16bit为单位      */
#define NetWobbleTestAddr_B         0x4029
#define NetWobbleTestDataLen_B      9                                   /*  数据长度 按16bit为单位      */

#define FT3WobbleTestAddr_A         0x4032
#define FT3WobbleTestDataLen_A      9                                   /*  数据长度 按16bit为单位      */
#define FT3WobbleTestAddr_B         0x403B
#define FT3WobbleTestDataLen_B      9                                   /*  数据长度 按16bit为单位      */


//FT3操作码
#define  FT3_CTL_SET_RECV_NUM_1 \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0341, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define  FT3_CTL_SET_RECV_NUM_2 \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0342, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define  FT3_CTL_SET_RECV_TIME_1\
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0343, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define  FT3_CTL_SET_RECV_TIME_2\
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0344, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define FT3_CTL_GET_RECV_1    \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0345, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define  FT3_CTL_GET_RECV_2  \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0346, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define  FT3_CTL_SET_RECV_LOOP_1  \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0347, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define  FT3_CTL_SET_RECV_LOOP_2   \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0348, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define  FT3_CTL_GET_RECV_LOOP_BUF_INDEX_1  \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0349, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define  FT3_CTL_GET_RECV_LOOP_BUF_INDEX_2  \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x034A, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define  FT3_CTL_STOP_RECV_LOOP_1           \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x034B, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define  FT3_CTL_STOP_RECV_LOOP_2           \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x034C, METHOD_BUFFERED, FILE_ANY_ACCESS)
                                                                        /*  设置光串口1的接收模式       */
#define  FT3_CTL_SET_FT3_1_MODE           \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x034D, METHOD_BUFFERED, FILE_ANY_ACCESS)

//以太网口 操作码
//smv
#if EN_SMV
#define   GET_SMV_CTL \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0381, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define  SMV_CTL_SET_RECV_NUM_1 \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0383, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define  SMV_CTL_SET_RECV_NUM_2 \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0384, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define  SMV_CTL_SET_RECV_TIME_1\
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0385, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define  SMV_CTL_SET_RECV_TIME_2\
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0386, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define SMV_CTL_GET_RECV_1    \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0387, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define  SMV_CTL_GET_RECV_2  \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0388, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define  SMV_CTL_SET_RECV_LOOP_1  \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0389, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define  SMV_CTL_SET_RECV_LOOP_2   \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x038A, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define  SMV_CTL_GET_RECV_LOOP_BUF_INDEX_1  \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x038B, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define  SMV_CTL_GET_RECV_LOOP_BUF_INDEX_2  \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x038C, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define  SMV_CTL_STOP_RECV_LOOP_1           \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x038D, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define  SMV_CTL_STOP_RECV_LOOP_2           \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x038E, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif
//goose
#if EN_9192_DETECT
#define   GOOSE_CTL_DETECT \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03C1, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define   GOOSE_CTL_FILTER \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03C2, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define  GOOSE_CTL_SET_RECV_NUM_1 \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03C3, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define  GOOSE_CTL_SET_RECV_NUM_2 \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03C4, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define  GOOSE_CTL_SET_RECV_TIME_1\
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03C5, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define  GOOSE_CTL_SET_RECV_TIME_2\
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03C6, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define GOOSE_CTL_GET_RECV_1    \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03C7, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define  GOOSE_CTL_GET_RECV_2  \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03C8, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define  GOOSE_CTL_SET_RECV_LOOP_1  \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03C9, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define  GOOSE_CTL_SET_RECV_LOOP_2   \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03CA, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define  GOOSE_CTL_GET_RECV_LOOP_BUF_INDEX_1  \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03CB, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define  GOOSE_CTL_GET_RECV_LOOP_BUF_INDEX_2  \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03CC, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define  GOOSE_CTL_STOP_RECV_LOOP_1           \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03CD, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define  GOOSE_CTL_STOP_RECV_LOOP_2           \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03CE, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

#if EN_GOOSE_DETECT
#define   GOOSE_FILTER_CTL_DETECT \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03E1, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define   GOOSE_FILTER_CTL_FILTER \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03E2, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define  GOOSE_FILTER_CTL_SET_RECV_NUM_1 \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03E3, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define  GOOSE_FILTER_CTL_SET_RECV_NUM_2 \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03E4, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define  GOOSE_FILTER_CTL_SET_RECV_TIME_1\
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03E5, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define  GOOSE_FILTER_CTL_SET_RECV_TIME_2\
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03E6, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define GOOSE_FILTER_CTL_GET_RECV_1    \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03E7, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define  GOOSE_FILTER_CTL_GET_RECV_2  \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03E8, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define  GOOSE_FILTER_CTL_SET_RECV_LOOP_1  \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03E9, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define  GOOSE_FILTER_CTL_SET_RECV_LOOP_2   \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03EA, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define  GOOSE_FILTER_CTL_GET_RECV_LOOP_BUF_INDEX_1  \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03EB, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define  GOOSE_FILTER_CTL_GET_RECV_LOOP_BUF_INDEX_2  \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03EC, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define  GOOSE_FILTER_CTL_STOP_RECV_LOOP_1           \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03ED, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define  GOOSE_FILTER_CTL_STOP_RECV_LOOP_2           \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x03EE, METHOD_BUFFERED, FILE_ANY_ACCESS)
#endif

//添加测试功能
#define IOCTRL_SET_ADDRESS       \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0303, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTRL_SET_CHN       \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0304, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTRL_READ_TEST_INFO    \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0308, METHOD_BUFFERED, FILE_ANY_ACCESS)